version: '3.9'

services:
  nuxt:
    container_name: nuxt
    build: docker/nuxt
    volumes:
      - ./front:/front:cached
      - ./front/node_modules:/front/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
      - "4000:4000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:                  # 追加
      - localhost:0.0.0.0   # 追加
    command: sh -c "npm run dev"